<style>
	#new-post-link {
		color: #fff;
		text-shadow: 0 -1px 0 rgba(0,0,0,0.25);
		background-color: #60b044;
		background-image: -moz-linear-gradient(#8add6d, #60b044);
		background-image: -webkit-linear-gradient(#8add6d, #60b044);
		background-image: linear-gradient(#8add6d, #60b044);
		background-repeat: repeat-x;
		border-color: #5ca941;
		padding: 0 10px;
		line-height: 24px;
		box-shadow: none;
		outline:none;
		position: relative;
		display: inline-block;
		font-size: 13px;
		font-weight: bold;
		white-space: nowrap;
		border-radius: 3px;
		border: 1px solid #ddd;
		vertical-align: middle;
		cursor: pointer;
		-webkit-user-select: none;
		-khtml-user-select: none;
		-moz-user-select: none;
		-ms-user-select: none;
		user-select: none;
		text-decoration:none;
	}
	#new-post-link {
		float:right;
	}
	#blog-admin-section-header:after {
		content:".";
		clear:both;
		display:block;
		height:0;
		padding:0;
		margin:0;
		overflow: hidden;
	}
	#post-table {
		border-radius: 2px;
		border: 1px solid #d8d8d8;
		border-collapse:collapse;
		width:100%;
	}
	#post-table a {
		display:block;
		padding: 8px 10px 8px 8px;
		text-decoration:none;
		color: #464646;
	}
	#post-table tr td {
		border-bottom: 1px solid #eee;
		background-color: #fafafb;
	}
	#post-table tr:last-child td {
		border-bottom: none;
	}
	#post-table tr:hover td {
		background-color:#fdfdfe;
	}
</style>
<div id="blog-admin-section-header">
	<h1 style="float:left;display:inline-block;"><?php echo $this->translate('Posts')?></h1>
	<a href="<?php echo $this->blogAdminUrl('posts/new');?>" id="new-post-link"><?php echo $this->translate("New Post")?></a>
</div>

<table id="post-table">
<?php foreach ($this->paginator as $post) : ?>
	<?php $edit_uri = $this->blogAdminUrl('posts/edit', array(), array('query' => array('s'=>$post->getSlug(), 'hl' => $post->getLanguage()))); ?>
	<tr>
		<td><a href="<?php echo  $edit_uri ?>"><?php echo $post->getTitle(); ?></a></td>
		<td><a href="<?php echo  $edit_uri ?>"><?php echo $post->getLanguage(); ?></a></td>
		<td><a href="<?php echo  $edit_uri ?>"><?php echo $post->getDateModified()->format('Y-m-d'); ?></a></td>
	</tr>
<?php endforeach; ?>
</table>

<?php
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'Blog'),
    // the route to link to when a user clicks a control link
    array(
        'route' => $this->route
    )
);
?>