<div id="blog-admin-section-header">
	<div class="admin-icon45 admin-icon45-posts"><br></div>
	<h1><?php echo $this->translate('Posts')?></h1>
	<a href="<?php echo $this->blogAdminUrl('post-new');?>" id="new-post-link" class="button minibutton primary"><?php echo $this->translate("New Post")?></a>
</div>

<div id="blog-items-table">
	<table id="post-table">
	<tr>
		<th>Title</th>
		<th>Language</th>
		<th>Author</th>
		<th>Date</th>
	</tr>
	<?php foreach ($this->paginator as $post) : ?>
		<?php 
			$edit_uri = $this->blogAdminUrl('post-edit', array('s'=>$post->getSlug(), 'hl' => $post->getLanguage()));
			$author   = $this->getPostAuthor($post->getAuthor()); 
		?>
		<tr>
			<td><a href="<?php echo  $edit_uri ?>"><?php echo $post->getTitle(); ?></a></td>
			<td><a href="<?php echo  $edit_uri ?>"><?php echo $post->getLanguage(); ?></a></td>
			<td><a href="<?php echo  $edit_uri ?>"><?php echo $this->zfcUserDisplayName($author) ?></a></td>
			<td><a href="<?php echo  $edit_uri ?>"><?php echo $post->getDateModified()->format('Y-m-d'); ?></a></td>
		</tr>
	<?php endforeach; ?>
	</table>
</div>
<?php
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('blog/backend/partial_paginator.phtml', 'Blog'),
    // the route to link to when a user clicks a control link
    array(
        'action' => 'posts'
    )
);
?>