<?php


$form     = $this->form;
$post     = $form->get('post');

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($post->get('title'));
echo $this->formRow($post->get('slug'));
//echo $this->formRow($post->get('categories'));
echo $this->formRow($post->get('excerpt'));
echo $this->formRow($post->get('content'));
echo $this->formElement($form->get('csrf'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();