<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Blog Admin'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/blog-admin.css');
         ?>

        <!-- Scripts -->
        <?php echo $this->headScript(); ?>

    </head>
    <body>
    	<div class="header">
    		<div class="container">
    			<a href="<?php echo $this->blogAdminUrl() ?>" id="header-logo"><span></span></a>
    			<ul id="top-nav">
    				<!-- <li class="categories"><a href=""><?php echo $this->translate('Categories')?></a></li>  -->
    				<li class="posts"><a href="<?php echo $this->blogAdminUrl(array('controller' => 'post', 'action' => 'index')) ?>"><?php echo $this->translate('Posts')?></a></li>
    			</ul>
    			<ul id="user-links">
    				<li>
    					<a href="<?php echo $this->url('zfcuser');?>" class="name">
    						<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 20)); ?>
    						<?php echo $this->zfcUserDisplayName() ?>
    					</a>
    				</li>
    				<li>
    					<a href="<?php echo $this->blogAdminUrl(array('controller' => 'post', 'action' => 'new'));?>" id="new-post">
    						<span class="blog-admin-icons new-post"></span>
    					</a>
    				</li>
    				<!-- TODO: Should be displayed only for admins -->
    				<li>
    					<a href="<?php echo $this->blogAdminUrl(array('controller' => 'settings', 'action' => 'index')) ?>" id="settings">
    						<span class="blog-admin-icons settings"></span>
    					</a>
    				</li>
    				<li>
    					<a href="<?php echo $this->url('zfcuser/logout');?>" id="logout">
    						<span class="blog-admin-icons logout"></span>
    					</a>
    				</li>
    			</ul>
    			
    		</div>
    	</div>
        <div class="container">
        	<div id="blog-container">
	            <?php echo $this->content; ?>
            </div>
            <hr style="margin-top:3em;">
	        <footer>
	        	<div class="container">
	                <p>&copy; 2005 - <?php echo date('Y') ?> by JPG-Consulting. <?php echo $this->translate('All rights reserved.') ?></p>
	            </div>
	        </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
